In [1]:
import torch

In [2]:
tensor = torch.Tensor([[3,4],[7,5]])
tensor

tensor([[3., 4.],
        [7., 5.]])

In [3]:
tensor.requires_grad

False

In [4]:
tensor.requires_grad_()

tensor([[3., 4.],
        [7., 5.]], requires_grad=True)

In [5]:
tensor.requires_grad

True

In [6]:
print(tensor.grad)

None


In [7]:
out = tensor * tensor

In [8]:
out.requires_grad

True

In [9]:
print(out.grad_fn)

In [10]:
out = (tensor * tensor).mean()
print(out.grad_fn)

In [11]:
out.backward()

In [12]:
print(tensor.grad)

tensor([[1.5000, 2.0000],
        [3.5000, 2.5000]])


In [13]:
new_tensor = tensor * tensor

In [14]:
print(new_tensor.requires_grad)

True


In [15]:
with torch.no_grad():
    new_tensor = tensor * tensor
    print(new_tensor.requires_grad)

False
