In [1]:
import torch
print(torch.__version__)

1.0.0


In [2]:
tensor_array = torch.Tensor([[1,2],[4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [3]:
tensor_uninitialized = torch.Tensor(3, 3)

In [5]:
torch.numel(tensor_uninitialized)

9

In [6]:
tensor_init = torch.rand(2,3)
tensor_init

tensor([[0.5411, 0.0851, 0.6602],
        [0.3043, 0.1950, 0.4761]])

In [7]:
tensor_int = torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  0],
        [ 0, -1,  0],
        [-1,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]], dtype=torch.int32)

In [8]:
tensor_zero = torch.zeros(10)
tensor_zero

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
init_tensor = torch.rand(3,3)
init_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [11]:
new_tensor = init_tensor.add(4)
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [12]:
import numpy as np

In [13]:
numpy_arr = np.array([1,2,3])
numpy_arr

array([1, 2, 3])

In [14]:
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3])

In [15]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [16]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [17]:
tensor

tensor([1, 4, 3])

In [18]:
numpy_from_tensor

array([1, 4, 3])

In [19]:
intial_tensor = torch.rand(2,3)
intial_tensor

tensor([[0.2735, 0.5871, 0.0351],
        [0.6491, 0.3612, 0.1798]])

In [20]:
intial_tensor[0,2]

tensor(0.0351)

In [21]:
intial_tensor[:,1:]

tensor([[0.5871, 0.0351],
        [0.3612, 0.1798]])

In [22]:
resized_tensor = intial_tensor.view(6)
resized_tensor.shape

torch.Size([6])

In [23]:
resized_tensor

tensor([0.2735, 0.5871, 0.0351, 0.6491, 0.3612, 0.1798])

In [24]:
intial_tensor[0,2] = 0.1111

In [25]:
resized_tensor

tensor([0.2735, 0.5871, 0.1111, 0.6491, 0.3612, 0.1798])

In [26]:
resized_tensor = intial_tensor.view(3,2)
resized_tensor.shape

torch.Size([3, 2])

In [27]:
resized_tensor

tensor([[0.2735, 0.5871],
        [0.1111, 0.6491],
        [0.3612, 0.1798]])

In [28]:
from torch.autograd import Variable
x = Variable(torch.randn(1,10))
h = Variable(torch.randn(1,20))
W_h = Variable(torch.randn(20,20))
W_x = Variable(torch.randn(20,10))
h_prod = torch.mm(W_h,h.t())
x_prod = torch.mm(W_x,x.t())
next_h = (h_prod + x_prod).tanh()
loss = next_h.sum()
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn